package:
  name: foo
  version: 1.2.3

build:
  noarch_python: True
  entry_points:
    - foo = foo:main

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - foo
  imports:
    - foo
